In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,56,34,78,2])

In [ ]:
arr, type(arr)

(array([ 1, 56, 34, 78,  2]), numpy.ndarray)

In [ ]:
arr.shape

(5,)

In [ ]:
arr.size #Number of elements in the array.

5

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.itemsize

8

In [ ]:
arr1 = np.array([12.3,123])

In [ ]:
arr1, arr1.dtype

(array([ 12.3, 123. ]), dtype('float64'))

In [ ]:
arr1.itemsize

8

In [ ]:
arr1 = np.array(['cdac',123])

In [ ]:
arr1, arr1.dtype

(array(['cdac', '123'], dtype='<U21'), dtype('<U21'))

In [ ]:
arr1.itemsize

84

In [ ]:
arr2d = np.array([[1,2],[3,4]]) #Number of elements in the array.

In [ ]:
arr2d.shape, arr2d.size, arr2d.dtype, arr2d.itemsize

((2, 2), 4, dtype('int64'), 8)

In [ ]:
arr2d = np.array([[1,2],[3,4],[1,2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
arr3d.shape, arr3d.size, arr3d.dtype,arr3d.itemsize

((2, 2, 2), 8, dtype('int64'), 8)

In [ ]:
arr = np.array([1,2,3],dtype='int8')

In [ ]:
arr.dtype

dtype('int8')

In [ ]:
arrComplex = np.array([1,2,3],dtype='complex')

In [ ]:
arrComplex

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
arrComplex.dtype, arrComplex.itemsize

(dtype('complex128'), 16)

In [ ]:
np.zeros((2,22))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
arr3d_zeros = np.zeros(arr3d.shape)

In [ ]:
arr3d_zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
np.empty((2,2,2,3),dtype='int')

array([[[[-4625196817309499392, -4620693217682128896,
                             0],
         [-4625196817309499392,  4598175219545276416,
          -4620693217682128896]],

        [[ 4602678819172646912, -4625196817309499392,
           4598175219545276416],
         [                   0,  4602678819172646912,
           4598175219545276416]]],


       [[[ 4598175219545276416,  4602678819172646912,
                             0],
         [ 4598175219545276416, -4625196817309499392,
           4602678819172646912]],

        [[-4620693217682128896,  4598175219545276416,
          -4625196817309499392],
         [                   0, -4620693217682128896,
          -4625196817309499392]]]])

# arange()

In [ ]:
myRange = np.arange(1,100,2)

In [ ]:
myRange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
myRange = np.arange(np.pi,np.pi*10,1)

In [ ]:
myRange

array([ 3.14159265,  4.14159265,  5.14159265,  6.14159265,  7.14159265,
        8.14159265,  9.14159265, 10.14159265, 11.14159265, 12.14159265,
       13.14159265, 14.14159265, 15.14159265, 16.14159265, 17.14159265,
       18.14159265, 19.14159265, 20.14159265, 21.14159265, 22.14159265,
       23.14159265, 24.14159265, 25.14159265, 26.14159265, 27.14159265,
       28.14159265, 29.14159265, 30.14159265, 31.14159265])

In [ ]:
myRange = np.arange(0.5,7.7,0.2)

In [ ]:
myRange

array([0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5, 2.7, 2.9,
       3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9, 5.1, 5.3, 5.5,
       5.7, 5.9, 6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5])

In [ ]:
myRange = np.arange(np.pi,10*np.pi,np.pi)

In [ ]:
myRange

array([ 3.14159265,  6.28318531,  9.42477796, 12.56637061, 15.70796327,
       18.84955592, 21.99114858, 25.13274123, 28.27433388])

# Special case if step is having rounding off error

In [ ]:
myRange = np.arange(0.5,1.9,0.7)

In [ ]:
myRange

array([0.5, 1.2])

In [ ]:
myRange = np.arange(0,4.9,0.7)

In [ ]:
myRange

array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9])

# linearly spaced values

In [ ]:
np.linspace(0,1,5) # create n-1 parts

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,20,5) # create n-1 parts

array([ 0.,  5., 10., 15., 20.])

# Arithmetic Operation

In [ ]:
arr1=np.array([100,345,678,3456])
arr2=np.array([12,15,78,90])

In [ ]:
arr1+ arr2

array([ 112,  360,  756, 3546])

In [ ]:
arr1 -  arr2

array([  88,  330,  600, 3366])

In [ ]:
arr1 * arr2

array([  1200,   5175,  52884, 311040])

In [ ]:
arr1 * 100

array([ 10000,  34500,  67800, 345600])

In [ ]:
arr1 / 40 * 89 + arr2 * 10 + 100

array([ 442.5  , 1017.625, 2388.55 , 8689.6  ])

# exercise


In [ ]:
m1=np.array([78,98,85])
m2=np.array([96,77,80])
m3=np.array([99,91,78])

In [ ]:
(m1+m2+m3)

array([273, 266, 243])

In [ ]:
# find percentage of every student

# create 2d array for all records and perform
#sum(), sum(axis=0), sum(axis=1)

In [ ]:
a2d = np.array([m1,m2,m3])
print(a2d)
a2d.sum()
a2d.sum(axis=0)
a2d.sum(axis=1)

In [57]:
np.array([m1,m2,m3])

array([[78, 98, 85],
       [96, 77, 80],
       [99, 91, 78]])

# Create array of random numbers

repeatition is allowed

In [ ]:
r_arr = np.random.randint(0,1000,(4,5))
#Return random integers from low (inclusive) to high (exclusive).

In [ ]:
r_arr

array([[386, 369, 479, 434, 692],
       [231, 639, 574, 947, 960],
       [794, 707,  60, 251, 162],
       [381, 495, 890, 552, 715]])

In [ ]:
r_arr = np.random.randint(0,5,(4,5))

In [ ]:
r_arr

array([[0, 0, 1, 4, 3],
       [0, 1, 1, 2, 4],
       [4, 1, 3, 1, 3],
       [4, 1, 4, 3, 2]])

In [ ]:
r_arr = np.random.rand(10)

In [ ]:
r_arr

array([0.36720218, 0.46364774, 0.34350872, 0.97500382, 0.9863011 ,
       0.35087207, 0.69281744, 0.63753812, 0.20959639, 0.43293244])

In [ ]:
r_arr = np.random.rand(10,2)

In [ ]:
r_arr

array([[0.01262599, 0.9494814 ],
       [0.82622568, 0.46301499],
       [0.48944604, 0.48884703],
       [0.29099759, 0.36450057],
       [0.27806269, 0.11650694],
       [0.48746134, 0.18578004],
       [0.63774534, 0.79260823],
       [0.12601857, 0.10895608],
       [0.58508431, 0.57200375],
       [0.39485091, 0.6118189 ]])

# Matrix Operations

In [ ]:
A = np.array([[1,2],[3,4]])

In [ ]:
B = np.array([[100,200],[300,400]])

In [ ]:
A*B # element wise multiplication

array([[ 100,  400],
       [ 900, 1600]])

In [ ]:
A@B

array([[ 700, 1000],
       [1500, 2200]])

In [ ]:
A.dot(B)

array([[ 700, 1000],
       [1500, 2200]])

# Universal Functions

https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

In [ ]:
A = np.array([[1,2],[3,4]])

In [ ]:
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
np.power(A,2)

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
np.sin(A)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [ ]:
np.cos(A)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

# Numpy special representations for floating point values

+inf    -> + infinity

-inf    -> - infinity

nan     -> Not a Number



# ravel

In [ ]:
r_arr = np.random.randint(0,1000,(2,2,2))

In [ ]:
for elem in r_arr:
    print("Element in array is : ")
    print(elem)

Element in array is : 
[[911 900]
 [735 174]]
Element in array is : 
[[582 855]
 [590 922]]


In [ ]:
for elem in r_arr.ravel():
    print("Element in array is : ")
    print(elem)

Element in array is : 
911
Element in array is : 
900
Element in array is : 
735
Element in array is : 
174
Element in array is : 
582
Element in array is : 
855
Element in array is : 
590
Element in array is : 
922


# Create a neuron in numpy

fun neuron has two parameters

x : input array ( size n)

w : weights (size n)

bias : its a single value / constant

x & w are of same size

Step1 : calculate their element wise multiplication

Step2 : calculate sum of above multiplication and add bias to it

Step3 : return the value



In [ ]:
def neuron(x,w,bias):
    X = x*w
    X = X.sum() + bias
    return X

In [ ]:
x= np.array([10,20,30])

In [ ]:
w=np.random.rand(x.shape[0])

In [ ]:
w

array([0.26809235, 0.01697488, 0.28201312])

In [ ]:
bias = 100

In [ ]:
neuron(x,w,bias)

111.48081472873571